all::
	g++ -Wno-macro-redefined -O3 -DDEBUG test.cpp -o ./a.out.debug
	g++ -Wno-macro-redefined -O3 test.cpp -o  ./a.out.nodebug

view::
	/opt/homebrew/opt/llvm/share/opt-viewer/opt-viewer.py test.opt.yaml
